### ISSUE TITLE
Support angular dart 5

### ISSUE THREAD

**Issue by dineshbhosale** [lejard-h/angular_recaptcha#12]
`pub get` freezes when I run following command : 

Many users can't develop their angular dart app without this component

```yaml
name: asdasd
description: asdasd
version: 0.0.1
environment:
  sdk: '>=2.0.0-dev.28.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+4
  angular_forms: ^1.0.1-alpha+2
  angular_router: ^2.0.0-alpha+2
  http: ^0.11.0
  stream_transform: ^0.0.6
  angular_recaptcha: ^0.0.1

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.7.10+1
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0
  test: ^0.12.30
```
